### ISSUE TITLE
Incorrect settings on first load of the plug-in window

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#11]
**Environment**
Windows 11 Home (build 22631.3447) and Bitwig 5.1.8

**Steps**
1 - Close the project with Sumu. Or Deactivate the plugin (In Bitwig I right clicked and unchecked Active).
2 - Re-open the project with Sumu. Or Reactive the plugin (In Bitwig I right clicked and checked Active).
3 - Open the plug-in window for Sumu

**Expected**
I expect to see the previous settings I had for the Sumu plug-in window, including the correct patch title, the previous window size and the correct partials visible.

**Actual**
The Sumu plug-in window is the default size, and says 'Default' instead of the name I gave my patch. In my recording it is displaying the correct Partials visuals, but I have seen it also display the wrong Partials.

**Observations**
Note that the Patch sound correct when I play it.

Also note that if I close the plug-in window and re-open it a second time that the window is now the expected size, and displays the correct patch name.

**Repro**
I can reproduce the incorrect window size and patch name consistently. Reproducing the issue with the Partials displaying incorrectly seems to be more inconsistent.

**Evidence**
I recorded this video:
https://github.com/madronalabs/sumu-issues/assets/2022056/8074d3cf-1c50-477e-a16f-51e924bf386e

**Comment by randyjonesworld** [comment]
Fixed
