### ISSUE TITLE
Incorrect Partials Loop Behaviour when cycling back to the Off mode

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#12]
**Environment**
Windows 11 Home (build 22631.3447) and Bitwig 5.1.8

**Steps**
1 - Load the attached preset + partials
2 - Deactivate Sumu plug-in
3 - Activate Sumu plug-in
4 - Play some notes while switching through the Loop modes in the Partials section
5 - Cycle through back to the 'off' loop mode

**Expected**
The Partials should be playing from the start of the sound.

**Actual**
The Partials continue to play at the onset position where the 'on' loop window _was_ previously.

**Observations**
When I deactivate and re-activate the Sumu plug-in, then the Partials correctly play at the start of the sound again.

**Repro**
I can reproduce this every time with my custom Vutu partials, but I can also reproduce it with Partials like the 'test tones/2hz-freq-mod'. 

**Evidence**
I recorded a couple videos, and attached the presets and original wav and Vutu files I created the partials from:

https://github.com/madronalabs/sumu-issues/assets/2022056/9e0ea68d-8c69-4ede-b0fd-0463480ef04e

https://github.com/madronalabs/sumu-issues/assets/2022056/6afd977c-cff3-4f34-9fe8-25566e43c305

[Thing Collect Quick Test Patch.zip](https://github.com/madronalabs/sumu-issues/files/15212683/Thing.Collect.Quick.Test.Patch.zip)

**Comment by randyjonesworld** [comment]
Fixed
