### ISSUE TITLE
Default Patch not loaded correctly on newly created instance

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#13]
**Environment**
Windows 11 Home (build 22631.3447) and Bitwig 5.1.8

**Steps**
1 - Add a new Sumu plug-in instance to a track
2 - Open the plug-in window
3 - Play some notes

**Expected**
The Default patch is loaded correctly with a patrials map and cable connections, and I can play notes and hear sound.

**Actual**
No sound plays. Also no Partials map is loaded and no cable connections are present.

**Observations**
I have to switch away and then back to the Default patch for it to load/play correctly.

**Repro**
This happens by every time I open a new instance.
Note that the second loading the plugin after re-setting the Default patch it behaves as expected.

**Evidence**
I recorded this video:

https://github.com/madronalabs/sumu-issues/assets/2022056/8d793378-9521-4a98-8375-928a23ff87f8

**Comment by BenPalc** [comment]
Note that the playback of the video in GitHub is muted by default

**Comment by randyjonesworld** [comment]
Fixed in 1.0b20
