### ISSUE TITLE
Sumu b13 - Harsh sound when Amp at 0 position

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#14]
Most of my patches sound very different in b13.
After experimenting for a while, I think I finally figured out the main issue - When the amp is at 0.00 and the FM is fully open, there is a nasty buzzing high pitch saw type noise.

**Environment**
Windows 11 Home (version 10.0.22631 Build 22631) and Bitwig 5.1.9
Sumu 1.0.0b13

**Steps**
1. Load the **ranoka/amoeba sonar ambient** preset (or recreate something similar to the video)
2. Note that the amp starts fully at 0.00 and the FM Gate is fully open.

**Expected**
Nice bubble texture type sound.

**Actual**
Nasty buzzing high pitch saw type noise.

**Observations**
This happens if the Sumu instance is activated with the amp already at 0.00, or if the instance is activated with the amp at a different value (like 1.00) and then adjusted back to 0.00.

**Repro**
I can reproduce this on all my patches I designed in b12 that have the amp at 0.00

**Evidence**
I uploaded some unlisted videos on YouTube for better quality:

Video 1: Sumu 1.0.0b13 - with the issue
https://youtu.be/UxcV_74KEGo

Video 2: Sumu 1.0.0b12 - without the issue for context
https://youtu.be/FXTF8ZnZSSI

Note - issue where patch name says 'Default' when reloading a plugin instead of the actual patch name also in the video.

**Comment by randyjonesworld** [comment]
Fixed in 1.0.0b15.
