### ISSUE TITLE
Stuck at 100% CPU load after Exporting or Bouncing

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#20]
Environment
Windows 11 Home (build 22631.3880) and Bitwig 5.2
Sumu b19 used - but I have experienced this in all previous versions, including b15

Steps
1 - Export or Bounce a sumu track

Expected
The sound exports faster than regular playback, and the CPU level returns back to normal afterwards.

Actual
Exporting takes longer than regular playback, and during recording the CPU is at 100%, and the CPU remains at 100% until the Sumu instance is disabled/removed.

Observations
I recorded the video in Bitwig, but I experience the same behaviour in FL Studio and Reaper.
My current work around is to record the audio while it plays in real time instead of exporting/bouncing.

Repro
This is happening consistently any time I Export or Bounce audio.

Evidence
I recorded this video:
https://youtu.be/km0Dep4-7MI

**Comment by randyjonesworld** [comment]
fixed for 1.0.0b20.
