### ISSUE TITLE
Change in x Vel behaviour between b15 and b19

### ISSUE THREAD

**Issue by BenPalc** [madronalabs/sumu-issues#21]
**Environment**
Windows 11 Home (build 22631.3880) and Bitwig 5.2
RTX 4070ti and 64GB RAM
Sumu b15 and b19

**Steps**
1 - Enable x Vel in the Envelope Module
2 - Connect the Gate input to the Envelope gate
3 - Hook up the Envelope to something you can hear change with different velocities (like, volume, pitch or mod index).
4 - Record some midi with varying velocity to play into Sumu

**Expected**
The sound output from b15 and b19 should sound the same when using the x Vel option in the Envelope Module

**Actual**
The sound from b15 and b19 is different, the x Vel in b19 seems to have a more pronounced/exaggerated affect. when hooked up to the volume it will be louder in b19 and if hooked up to the pitch, the pitch will change more in b19 with different velocities.

**Observations**
The sounds appear to be the same if x Vel is disabled

**Repro**
All my sounds from b15 using the x Vel sound different in b19

**Evidence**
I recorded this video:
https://youtu.be/2Q4yATiqKg8

**Bonus video** - comparing my percussion presents from b15 and b19!
I also notice that some sounds that don't have x Vel set sound different, like the reverb on the Clap is very different, and the Hat sounds a bit different.
https://youtu.be/r55-_GW6L3w

**The Patch I used:**
[Test XVel FM.zip](https://github.com/user-attachments/files/16575506/Test.XVel.FM.zip)

**Comment by randyjonesworld** [comment]
This was a change but seems to be a worthwhile one going forward.
